### ISSUE TITLE
Implement Diffusion Controller

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-controller#11]
## Description

To render a complex Component Descriptor which may contain nested references it is necessary to introduce an orchestration controller. This controller will iterate over the resources in a given Component Descriptor and generate a processing pipeline for each resource. We shall call this process Diffusion because it takes the highly concentrated representation of a Component and diffuses the constituent resources through the processing pipeline into the target environment. 
 
The `spec.resourceSelector` field is used to define the resources which will be processed, it can skip the root resource ensuring that configuration resources are not processed and provides a selector field that enables filtering of resources by type or identity fields.

The `spec.pipelineTemplateRef` field references a yaml manifest which is stored in the Component Descriptor, likely in the root. It is a configuration file that will be used by the Diffusion controller to generate any Kubernetes resources that are necessary to deploy a particular OCM Resource. The template can use variables such as the component or resource name. The various steps in the diffusion pipeline can communicate using Snapshots. The below example illustrates a set of Kubernetes resources that would be generated for each resource in a component:

```yaml
apiVersion: config.ocm.software/v1alpha1
kind: DiffusionPipelineTemplate
metadata:
  name: pipeline-template
  labels:
    env: test
parameters:
  name: "{{ component }}-{{ resource }}"
steps:
- name: localize
  template:
    apiVersion: ocm.software/v1alpha1
    kind: Localization
    metadata:
      name: "{{ parameters.name }}"
    spec:
      sourceRef:
        kind: ComponentVersion
        name: "{{ component }}"
        resource: "{{ resource }}"
      configRef:
        kind: ComponentVersion
        name: "{{ component }}"
        resource:  ocm-config
        path: localization # default
      snapshotTemplate:
          name: "{{ parameters.name }}-localized"
- name: configure
  template:
    apiVersion: ocm.software/v1alpha1
    kind: Configuration
    metadata:
      name: "{{ parameters.name }}"
    spec:
      sourceRef:
        kind: Snapshot
        name: my-snapshot
        resource: "{{ parameters.name }}-localized"
      configRef:
        kind: ComponentVersion
        name: "{{ component }}"
        resource: ocm-config
        path: configuration # default
      values: 
         # populated from pipeline.values[resource]
      snapshotTemplate:
          name: "{{ parameters.name }}-config"
- name: flux-source
  template:
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: OCIRepository
    metadata:
      name: "{{ parameters.name }}"
    spec:
      interval: 10m0s
      url: "oci://{{ registry.addr }}/{{ parameters.name }}-config"
      ref:
        tag: latest
- name: flux-kustomization
  template:
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    metadata:
      name: "{{ parameters.name }}"
    spec:
      interval: 10m0s
      sourceRef:
        kind: OCIRepository
        name: "{{ component }}-{{ resource }}"
      path: "./"
      prune: true
```
Given a component containing database, backend and frontend resources the above pipeline would produce the following result

```mermaid
graph LR

diffusion --> database
diffusion --> backend
diffusion --> frontend

database --> locdb(Localization) --> dbsnap((snapshot)) --> confcdb(Configuration) --> confsnap((snapshot)) --> dbsrc(OCIRepository) --> dbkust(Kustomization)
backend --> locbe(Localization) --> besnap((snapshot)) --> confbe(Configuration) --> beconfsnap((snapshot)) --> besrc(OCIRepository) --> bekust(Kustomization)
frontend --> locfe(Localization) --> fesnap((snapshot)) --> conffe(Configuration) --> feconfsnap((snapshot)) --> fesrc(OCIRepository) --> fekust(Kustomization)
```

## CRD

```yaml
apiVersion: ocm.software/v1alpha1
kind: Diffusion
metadata:
    name: test
spec:
    # resources from this component will diffused
    componentRef:
        name: my-component
    resourceSelector: # process resources matching this selector
        skipRoot: true
        followReferences: true
        matchSelector:
        - field: type
          values: 
          - HelmChart
    pipelineTemplateRef: # send each resource through this pipeline
        name: my-component
        resource: pipeline-template
    values: # values are indexed by the resource name
        database:
          port: 27017
        frontend:
          color: "blue"
    #valuesFrom: # optionally the values could be provided via ConfigMap
```
