### ISSUE TITLE
OCM-ify Sockshop

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-controller#12]
## Description

Sock Shop is a polyglot micro-services application created by Wevaeworks for demonstration purposes.

For reInvent we should model it using OCM. Sock Shop should be modelled by creating a single **root** descriptor which contains `references` to dedicated descriptors for each micro-service.

The Component Descriptor for each micro-service should contain the following resources at a minimum:
- the manifests / Helm charts required to deploy the service
- the images required to deploy the service
- a ConfigData manifest (see below) that can be used to configure and localize the service

## ConfigData

```yaml
apiVersion: config.ocm.software/v1alpha1
kind: ConfigData
metadata:
  name: ocm-config
  labels:
    env: test
configuration:
- target: 
      name: manifests # the resource to target  defaults:
    color: red
    message: Hello, world!
  schema:
    type: object
    additionalProperties: false
    properties:
      namespace:
        type: string
      color:
        type: string
      message:
        type: string
  rules:
  - value: (( color ))
    file: configmap.yaml
    path: data.PODINFO_UI_COLOR
  - value: (( message ))
    file: configmap.yaml
    path: data.PODINFO_UI_MESSAGE
localization:
- target: 
      name: manifests # the resource to target
  rules:
  - resource:
      name: podinfo
    file: deploy.yaml
    image: spec.template.spec.containers[0].image
```

**note**: There is some prior art here: https://github.com/gardener/landscaper-examples/tree/master/sock-shop/many-components.
