### ISSUE TITLE
Tar single files

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm-controller#150]
Right now, we expect everything to be a tar. In order to avoid having to deal with single files which are not tarred and can be untarred to a filesystem, we will do the following: Detect if incoming stream is a tar, if not, tar it.

**Comment by Skarlso** [comment]
This is harder than it looks because we don't know the name of the file content that has been sent our way.

**Comment by Skarlso** [comment]
Somehow need to obtain the `path` data.

```yaml
    - name: config
      type: PlainText
      input:
        type: file
        path: "config.yaml"
        compress: true

```

**Comment by mohammad-ammar14** [comment]
Please find the Github link I have tried out below.
Github link: https://github.com/mohammad-ammar14/ocm-que/blob/main/db-config.yaml

**Comment by Skarlso** [comment]
Yes. So.

```yaml
    - name: db-deployment
      type: PlainText
      input:
        type: file
        path: "manifests/db-deployment.yaml"
        compress: true
```

Put this into a folder. Something like that thing I posted in your other issue.
