### ISSUE TITLE
Failed to build tar file when having multiple files in a folder

### ISSUE THREAD

**Issue by mayankraipure12** [open-component-model/ocm-controller#182]
![image](https://user-images.githubusercontent.com/120610939/235490060-81147f2e-f7cc-4f33-8aa3-00d029a74dff.png)

You can refer the example 
https://github.com/mayankraipure12/booker-ocm-component
where database folder have multiple files
namly , 
configMaps.yaml 
database-deployment.yaml
database-service.yaml

When try to create component and deploy via flux it fails to build tar.
This works fine if I have only file database-deployment.yaml ,
Is ocm support such a use case where all the configuration of kubernetes for a deployment can be put it to a single folder and then deploy automatically hence reduce the time , otherwise I have to run configMaps and database service via explicitly kubectl command.

**Comment by Skarlso** [comment]
<img width="641" alt="Screenshot 2023-05-02 at 10 22 56" src="https://user-images.githubusercontent.com/182850/235616252-e0a2ff7f-3634-40a2-add0-6fcb39be8f3d.png">

The configuration information for the localization is commented out. Any reason for that? It won't localise if it doesn't know how.

**Comment by Skarlso** [comment]
Also, the resource is misnamed.

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: booker-deployment
  namespace: ocm-system
spec:
  interval: 10m0s
  componentVersionRef:
    name: booker
    namespace: ocm-system
  resource:
    name: db
  snapshotTemplate:
    name: booker-deployment
```

The `resource` name in the component is named `deployment` and not `db`. Please fix it and try again.
