### ISSUE TITLE
RFC: WASM Proposal

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-controller#195]
## Proposal

We propose a change to the architecture of the ocm-controller that will introduce Web Assembly (WASM) middleware in order to transform OCM resources.

## Context

One of the design guidelines for the ocm-controller is that it should support arbitrary transformation of resources. Standard transformations such as Localization and Configuration are provided "in-tree" as part of the controller.

We currently perform transformation using code that is common to both Localization and Configuration controllers. In addition we share resources using Snapshots. Snapshots provide a generic way to pass OCM resources between different Kubernetes controllers.

Whilst this works it requires operators to manage a large number of Custom Resources generating additional complexity meaning it can be difficult to build a mental model of the transformation sequence. It also leads to a somewhat large and complex codebase.

## WASM Solution

WASM produces tiny binaries that execute in a sandboxed runtime environment. These properties make it ideal for the execution of untrusted code in a dynamic way. We propose that rather than using discrete controllers to perform transformation of OCM resources we can use WASM binaries to execute the transforms. WASM binaries can be executed from the ocm-controller and specified by the operator in the `Resource` CR.

In order for this solution to work we need to define a contract that WASM binaries and the ocm-controller must observe:

- 1: The WASM binary must be stored as a resource in an OCM component with type `webAssembly`
- 2: By default the ocm-controller will mount a file-system at the path `/data`  in which resources files will be available (this can be disabled if desired)
- 3: Any transformations should be performed on the filesystem
- 4: The ocm-controller will provide host calls that can be used to call ocm library functions such as `GetResourceBytes`, `GetResourceMeta`, `GetResourceAccess`. These host calls will be documented on the ocm website.
- 5: Configuration can be passed to the WASM guest process using the `values` or `valuesFrom` fields.

WASM transformations will be known as **middleware**.

The OCM project would provide a component that publishes **official** / **first-party** middleware.

This could include operations such as `spiff` based localization and configuration, `ocm://` prefix based localization and other transformations.

End-users could provide their own middleware by publishing the component and specifying the details in the Resource manifest.

The output of a resource would continue to be a `Snapshot` that is applied by `FluxDeployer` Custom Resources.

## API Changes

The API changes would be as follows:

- Localization & Configuration objects removed

- Resource CR updated to contain `spec.middleware` field:

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: podinfo-deployment
  namespace: ocm-system
spec:
  interval: 10m0s
  resourceRef:
    name: manifests
    component: delivery.ocm.software/middleware:v1.0.0
  middleware:
  - name: localizer
    component: delivery.ocm.software/middleware:v1.0.0
    values:
      prefix: ocm://
  - name: configure
    component: delivery.ocm.software/middleware:v1.0.0
    values:
      owned-by: "ocm.software"
      managed-by: "weaveworks"
```

**Comment by souleb** [comment]
how would we provide the runtime environment needed to execute the `middlewares`?  Also do we need to keep the `fs` around or is it available only for the reconciliation interval?

**Comment by Skarlso** [comment]
The fs is a throwaway as far as I understand. Since we basically do the thing, then the result gets put into the OCI cache. So whatever was there will probably be cleaned once done by a defer os.RemoveAll.

**Comment by Skarlso** [comment]
>how would we provide the runtime environment needed to execute the middleware?

I thought it's just super small binaries that we are going to execute as is?

```yaml
resources:
- name: ocm-localizer
  type: blob
  input:
    type: file
    path: ./bin/localizer
```
