### ISSUE TITLE
RFC: WASM based ResourcePipeline

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-controller#233]
## Description

This RFC supersedes  #195.

We propose a change to the architecture of the ocm-controller that will introduce Web Assembly (WASM) middleware in order to transform OCM resources.

In #195 we proposed modifying the existing `Resource`   controller to achieve this aim. However because the functionality of WASM lends itself to transformation pipelines we propose to introduce a new Kubernetes resource `ResourcePipeline` .  This will allow for the delivery of resources to arbitrary environments using WASM based delivery modules. This enables us to generalize the utility of the `ocm-controller` beyond Kubernetes.

## Context
One of the design guidelines for the ocm-controller is that it should support arbitrary transformation of resources. Standard transformations such as Localization and Configuration are provided "in-tree" as part of the controller.

We currently perform transformation using code that is common to both Localization and Configuration controllers. In addition we share resources using Snapshots. Snapshots provide a generic way to pass OCM resources between different Kubernetes controllers.

Whilst this works it requires operators to manage a large number of Custom Resources generating additional complexity meaning it can be difficult to build a mental model of the transformation sequence. It also leads to a somewhat large and complex codebase.

## WASM Solution

WASM produces tiny binaries that execute in a sandboxed runtime environment. These properties make it ideal for the execution of untrusted code in a dynamic way. We propose that rather than using discrete controllers to perform transformation of OCM resources we can use WASM binaries to execute the transforms. WASM binaries can be executed from the ocm-controller and specified by the operator in the `Resource` CR.

In order for this solution to work we need to define a contract that WASM binaries and the ocm-controller must observe:

- 1: The WASM binary must be stored as a resource in an OCM component with type `webAssembly`
- 2: By default the ocm-controller will mount a file-system at the path `/data`  in which resources files will be available (this can be disabled if desired)
- 3: Any transformations should be performed on the filesystem
- 4: The ocm-controller will provide host calls that can be used to call ocm library functions such as `GetResourceBytes`, `GetResourceMeta`, `GetResourceAccess`. These host calls will be documented on the ocm website.
- 5: Configuration can be passed to the WASM guest process using the `values` or `valuesFrom` fields.

The OCM project would provide a component that publishes **official** / **first-party** modules.

These modules could offer functionality such as `spiff` based localization and configuration, `ocm://` prefix based localization and other transformations.

End-users could provide their own modules by publishing the component and specifying the details in the ResourcePipeline manifest.

## Delivery & Secrets Integration

In order to support off-Kubernetes systems the `ResourcePipeline` spec can specify a set of delivery targets. The mechanics for transferring a resource to a target are the the responsibility of the delivery modules. The output of the workflow process can be transferred to multiple targets. 

In order to access target we provide access to secrets which are retrieved from secret stores and passed to the WASM module at the time of execution. In order to realize this functionality we will leverage the SecretStores API provided by the [External Secrets Operator](https://external-secrets.io/latest/).

## API Object

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: ResourcePipeline
metadata:
  name: podinfo-deployment
  namespace: ocm-system
spec:
  interval: 10m0s
  serviceAccountName: blue-team
  sourceRef: # the source must be a Kubernetes API object of kind ComponentVersion
    name: podinfo
    namespace: default
    resource: manifests
  secrets:
  - name: kubeconfig
    secretStoreRef: # ideally we can use ESO here
      name: vault
      namespace: default
    remoteRef:
      key: /kv/prod/kubeconfig
  - name: sshkey
    secretStoreRef:
      name: vault
      namespace: default
    remoteRef:
      key: /kv/prod/sshkey
  # parameters can be used to provided configuration that is
  # shared across multiple workflow steps
  parameters:
    replicas: 2
# parameters could also come from a configmap
# parametersFrom:
#   kind: ConfigMap
#   name: params
#   namespace: default
# workflows could be templated and re-used
# workflowRef:
#   name: release-workflow
  workflow:
    steps:
    - name: resolver
      module: delivery.ocm.software/middleware:v1.0.0@resolver
      # configuration values can be validated using cue policy that is part of the component
      values:
        prefix: ocm://
    - name: configure
      registry: ghcr.io/phoban01 # registry is optional, defaults to ghcr.io/open-component-model
      module: delivery.ocm.software/middleware:v1.0.0@configure
      values:
        replicas: $parameters.replicas
    - name: label
      module: delivery.ocm.software/middleware:v1.0.0@labeler
      values:
        owned-by: "ocm.software"
        managed-by: "weaveworks"
  delivery:
    targets:
    - name: local
      module: delivery.ocm.software/ssa:v1.0.0@ssa
      values:
        targetNamespace: default
        createNamespace: true
    - name: remote
      module: delivery.ocm.software/ssa:v1.0.0@ssa
      values:
        kubeconfig: $secrets.kubeconfig
    - name: oci
      module: delivery.ocm.software/oci:v1.0.0@push
      values:
        name: my-resource
        tag: release
        kubeconfig: $secrets.regcred
    - name: git
      module: delivery.ocm.software/git:v1.0.0@push
      values:
        repository: my-resource
        sshkey: $secrets.gitssh
        message: "[ocm-controller] add resources"
    - name: lambda
      module: delivery.ocm.software/aws:v1.0.0@lambda
      values:
        credentials: $secrets.aws
```

**Comment by Skarlso** [comment]
Could use a bit better explanation on the workflow part:

```yaml
workflow:
    steps:
    - name: resolver
      module: delivery.ocm.software/middleware:v1.0.0@resolver
      # configuration values can be validated using cue policy that is part of the component
      values:
        prefix: ocm://
    - name: configure
      registry: ghcr.io/phoban01 # registry is optional, defaults to ghcr.io/open-component-model
      module: delivery.ocm.software/middleware:v1.0.0@configure
      values:
        replicas: $parameters.replicas
    - name: label
      component: delivery.ocm.software/middleware:v1.0.0@labeler
      values:
        owned-by: "ocm.software"
        managed-by: "weaveworks"
```

So module appears to be optional, right? What's the module, if not defined? You define component instead. Did you just leave off module? Or would be somehow auto-discovered?

What is the purpose of `component` if defined? What is it if not defined? :)
