### ISSUE TITLE
Input elements that don't have corresponding defaults are ignored.

### ISSUE THREAD

**Issue by dee0** [open-component-model/ocm-controller#353]
For my component there are values for which no default is possible.   Because of this I attempted to omit them from configuration.defaults.   However I found that without the default my input values is ignored.

e.g.   I have a value 'vaultServerHostName' and there is reasonable default for this, so I don't have an entry for it in my ConfigData's configuration.defaults.  I do however have a rule for mapping it into my values.yaml that is in my component.    And then I have ConfigMap has my configuration source and in the appropriate spot in there I place 
  vaultServerHostName: [some uri]
.    While this seems a reasonable config vaultServerHostname from my ConfigMap will be ignored.

The reason for this is the loop here 
https://github.com/open-component-model/ocm-controller/blob/release-v0.6.0/controllers/mutation_reconcile_looper.go#L346
You can see that the code is only using top level elements of my supplied config for which there are matching top level elements in defaults.

Really didn't expect this.

There is a comment in the code 'must be a better way'.   I have much experience with helm and so I would find it most intuitive if if merged the defaults and the input values like helm merged dictionaries.   However after playing with spiff I found it doesn't do this very well.  

I did manage to put together that merged two dictionaries as I would expect.   Not sure if this could be applied within ocm-controller.

```
map1:
  key1: value1 
  key2: value2 
  child:
    ckey1: cvalue1
    ckey2: cvalue2
  
map2:
  <<<: (( &template &temporary ))
  key2: (( &default ( "updated_value2" ) ))
  key3: (( &default ( "value3" ) ))
  child:
    <<<: (( &default ))
    ckey2: (( &default ( "cupdated_value2" ) ))
    ckey3: (( &default ( "cvalue3" ) ))
    
merged_map: (( merge(map1, *map2) ))

```
