### ISSUE TITLE
README.md - deployer.yaml - error invalid: spec.interval

### ISSUE THREAD

**Issue by stb1337** [open-component-model/ocm-controller#363]
Following https://github.com/open-component-model/ocm-controller to the point of:

"Create a FluxDeployer to apply the Resource and save it to a file named deployer.yaml:"
```
# deployer.yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: podinfo-deployment
  kustomizationTemplate:
    interval: 10m0s
    path: ./
    prune: true
    targetNamespace: default
```

I get this error:

```
k apply -f examples/00-my-own/deployer.yaml
The FluxDeployer "podinfo" is invalid: spec.interval: Required value
```

fixed it to:

```
# deployer.yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: podinfo-deployment
  kustomizationTemplate:
    path: ./
    prune: true
    targetNamespace: default
```
