### ISSUE TITLE
`kind: Resource` - `version: latest` -> k8s events `Message Applied version: %!s(MISSING)`

### ISSUE THREAD

**Issue by stb1337** [open-component-model/ocm-controller#368]
Using `kind: Resource` with `version: latest` e.g.:

```
# resource.yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: ocm-hello-world-pod-info
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: ComponentVersion
    name: ocm-hello-world-pod-info
    namespace: ocm-system
    resourceRef:
      name: pod-info-chart
      version: latest
      extraIdentity:
        helmChart: podinfo # name of the chart
```
Following message in k8s events appears:
![image](https://github.com/open-component-model/ocm-controller/assets/5519671/188a9049-8886-451d-a50d-9874e586208d)

When `version: 6.6.0` is specified, it doesn't seem to publish a k8s event.
[UPDATE]: Even with `version: 6.6.0` k8s event `Applied version: %!s(MISSING)` appears.
