### ISSUE TITLE
private oci repos is not accessible despite setting `kind: ComponentVersion` `spec.repsoitory.secretRef`

### ISSUE THREAD

**Issue by stb1337** [open-component-model/ocm-controller#371]
kind/bug ?

I was not able that `ocm-controller` can pull OCI image from my private Github.com repo despite having created a k8s secret with a Github.com access token and setting `kind: ComponentVersion` `spec.repsoitory.secretRef`

```
export GITHUB_USER=stb1337 && export GITHUB_TOKEN=ghp_... && export GITHUB_USER_EMAIL=s....r@.....
kubectl create secret docker-registry pull-secret -n ocm-system \
    --docker-server=ghcr.io \
    --docker-username=$GITHUB_USER \
    --docker-password=$GITHUB_TOKEN \
    --docker-email=$GITHUB_USER_EMAIL
---
---
apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: ocm-hello-world-ingress-nginx
  namespace: ocm-system
spec:
  component: ocm.software/nginx-controller
  interval: 10s
  references:
    expand: true
  repository:
    url: "ghcr.io/stb1337/ocm-hello-world"
    secretRef:
      name: pull-secret
  version:
    semver: "1.10.0"
---
# resource.yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: ocm-hello-world-ingress-nginx
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: ComponentVersion
    name: ocm-hello-world-ingress-nginx
    namespace: ocm-system
    resourceRef:
      name: nginx-controller-chart
      version: "4.10.0"
      extraIdentity:
        helmChart: ingress-nginx # name of the chart
---
# deployer.yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: ocm-hello-world-ingress-nginx
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: ocm-hello-world-ingress-nginx
  kustomizationTemplate:
    path: ./
    prune: true
    targetNamespace: default
```
![image](https://github.com/open-component-model/ocm-controller/assets/5519671/a74efb91-23ad-4ac0-a7ba-34c0ac8f3784)

**environment**:
```
ocm version
{"Major":"0", "Minor":"7", "Patch":"0", "PreRelease":"", "Meta":"", "GitVersion":"0.7.0", "GitCommit":"a2b9f7464074572632c40feb4db19c65b5cedd94", "GitTreeState":"", "BuildDate":"2024-02-23T17:20:54Z", "GoVersion":"go1.21.7", "Compiler":"gc", "Platform":"darwin/arm64"}

 sw_vers
ProductName:		macOS
ProductVersion:		14.3.1
BuildVersion:		23D60

system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.3.1 (23D60)
      Kernel Version: Darwin 23.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ....
      User Name: sb (I5....)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: X Tage, 1 Stunde und 28 Minuten
```
