### ISSUE TITLE
`manifest does not contain minimum number of descriptors (2), descriptors found: 1`

### ISSUE THREAD

**Issue by stb1337** [open-component-model/ocm-controller#375]
Error:
```
HelmChart 'ocm-system/ocm-system-ocm-hello-world-pod-info-file-system-tar' is not ready: chart pull error: failed to download chart for remote reference: failed to get 'oci://registry.ocm-system.svc.cluster.local:5000/sha-2684113188136592673/podinfo:6.6.2': manifest does not contain minimum number of descriptors (2), descriptors found: 1
```

Setup:
```yaml
#components.yaml
components:
- name: ${COMPONENT_NAME_PREFIX}/pod-info
  labels:
  - name: "org.opencontainers.image.source"
    value: "https://github.com/stb1337/ocm-hello-world"  
  version: *version
  provider:
    name: ${PROVIDER}
  resources:
  - name: pod-info-external-helm-chart
    type: helmChart
    version: *version
    relation: external
    access:
      type: helm
      helmChart: podinfo:6.6.0
      helmRepository: https://stefanprodan.github.io/podinfo
  - name: pod-info-file-system-tar
    type: fileSystem
    version: *version
    relation: local
    input:      
      type: helm
      path: podinfo-6.6.0.tar
  - name: pod-info-image
    type: ociImage
    version: *version
    access:
      type: ociArtifact
      imageReference: ghcr.io/stefanprodan/podinfo:6.6.0
---
# settings.yaml
VERSION: 0.0.10
NAME: ocm-hello-world
COMPONENT_NAME_PREFIX: ocm.software
PROVIDER: stb1337
---
```

Building+pushing OCM OCI image..

```shell
ocm add componentversions --create --file ocm-hello-world --settings settings.yaml components.yaml
processing components.yaml...
  processing document 1...
    processing index 1
    processing index 2
    processing index 3
found 3 components
adding component ocm.software/ocm-hello-world:0.0.10...
  adding reference ocm.software/nginx-controller: "name"="nginx-controller","version"="1.10.2"...
  adding reference ocm.software/pod-info: "name"="pod-info","version"="6.6.2"...
adding component ocm.software/nginx-controller:1.10.2...
  adding resource helmChart: "name"="nginx-external-helm-chart","version"="1.10.2"...
  adding resource fileSystem: "name"="nginx-file-system-tgz","version"="1.10.2"...
adding component ocm.software/pod-info:6.6.2...
  adding resource helmChart: "name"="pod-info-external-helm-chart","version"="6.6.2"...
  adding resource fileSystem: "name"="pod-info-file-system-tar","version"="6.6.2"...
  adding resource ociImage: "name"="pod-info-image","version"="6.6.2"...
ocm transfer commontransportarchive --copy-resources --enforce --overwrite ./ocm-hello-world OCIRegistry::ghcr.io/stb1337/ocm-hello-world
transferring component "ocm.software/nginx-controller"...
  transferring version "ocm.software/nginx-controller:1.10.2"...
    version "ocm.software/nginx-controller:1.10.2" already present -> skip transport
transferring component "ocm.software/ocm-hello-world"...
  transferring version "ocm.software/ocm-hello-world:0.0.10"...
    version "ocm.software/ocm-hello-world:0.0.10" already present -> skip transport
transferring component "ocm.software/pod-info"...
  transferring version "ocm.software/pod-info:6.6.2"...
  warning:   version "ocm.software/pod-info:6.6.2" already present, but differs because some artifacts and signature relevant properties have been changed (transport enforced by overwrite option)
  ...resource 0 pod-info-external-helm-chart[helmChart] (already present)
  ...resource 1 pod-info-file-system-tar[fileSystem](ocm.software/pod-info/podinfo:6.6.0) (already present)
  ...resource 2 pod-info-image[ociImage](stefanprodan/podinfo:6.6.0)...
  ...adding component version...
➜  ocm-hello-world git:(main) ✗ k apply -f k8s-component-version/03-pod-info.yaml
componentversion.delivery.ocm.software/ocm-hello-world-pod-info unchanged
resource.delivery.ocm.software/ocm-hello-world-pod-info-external-helm-chart unchanged
fluxdeployer.delivery.ocm.software/ocm-hello-world-nginx-external-helm-chart created
resource.delivery.ocm.software/ocm-hello-world-pod-info-file-system-tar unchanged
fluxdeployer.delivery.ocm.software/ocm-hello-world-pod-info-file-system-tar unchanged
➜  ocm-hello-world git:(main) ✗ k apply -f k8s-component-version/03-pod-info.yaml
componentversion.delivery.ocm.software/ocm-hello-world-pod-info unchanged
resource.delivery.ocm.software/ocm-hello-world-pod-info-external-helm-chart unchanged
fluxdeployer.delivery.ocm.software/ocm-hello-world-nginx-external-helm-chart unchanged
resource.delivery.ocm.software/ocm-hello-world-pod-info-file-system-tar unchanged
fluxdeployer.delivery.ocm.software/ocm-hello-world-pod-info-file-system-tar created

```

Using `ocm-controller` to deploy Helm Chart which is stored in resource `pod-info-external-helm-chart` which is build by referencing external helm chart repository:

```yaml
---
apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: ocm-hello-world-pod-info
  namespace: ocm-system
spec:
  component: ocm.software/pod-info
  interval: 10s
  references:
    expand: true
  repository:
    url: ghcr.io/stb1337/ocm-hello-world
    secretRef:
      name: pull-secret
  version:
    semver: "6.6.2"
---
# resource.yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: ocm-hello-world-pod-info-external-helm-chart
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: ComponentVersion
    name: ocm-hello-world-pod-info
    namespace: ocm-system
    resourceRef:
      name: pod-info-external-helm-chart
      version: "6.6.2"
      extraIdentity:
        helmChart: podinfo # name of the chart
---
# deployer.yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: ocm-hello-world-nginx-external-helm-chart
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: ocm-hello-world-pod-info-external-helm-chart
  helmReleaseTemplate:
    chart: 
      spec: 
        chart: "podinfo"
        interval: 10s
        sourceRef:
          apiVersion: delivery.ocm.software/v1alpha1
          kind: Resource
          name: ocm-hello-world-pod-info-external-helm-chart
    interval: 10s
    releaseName: "pod-info-external-helm-chart"
    targetNamespace: default

```

Using `ocm-controller` to deploy Helm Chart which is stored in resource `pod-info-file-system-tar` which is build by referencing local tar file which contains packed helm chart:

```yaml
---
apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: ocm-hello-world-pod-info
  namespace: ocm-system
spec:
  component: ocm.software/pod-info
  interval: 10s
  references:
    expand: true
  repository:
    url: ghcr.io/stb1337/ocm-hello-world
    secretRef:
      name: pull-secret
  version:
    semver: "6.6.2"
---
# resource.yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: ocm-hello-world-pod-info-file-system-tar
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: ComponentVersion
    name: ocm-hello-world-pod-info
    namespace: ocm-system
    resourceRef:
      name: pod-info-file-system-tar
      version: "6.6.2"
      extraIdentity:
        helmChart: podinfo # name of the chart
---
# deployer.yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: ocm-hello-world-pod-info-file-system-tar
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: ocm-hello-world-pod-info-file-system-tar
  helmReleaseTemplate:
    chart: 
      spec: 
        chart: "podinfo"
        interval: 10s
        sourceRef:
          apiVersion: delivery.ocm.software/v1alpha1
          kind: Resource
          name: ocm-hello-world-pod-info-file-system-tar
    interval: 10s
    releaseName: "pod-info-file-system-tar"
    targetNamespace: default    
```

Error:
```
HelmChart 'ocm-system/ocm-system-ocm-hello-world-pod-info-file-system-tar' is not ready: chart pull error: failed to download chart for remote reference: failed to get 'oci://registry.ocm-system.svc.cluster.local:5000/sha-2684113188136592673/podinfo:6.6.2': manifest does not contain minimum number of descriptors (2), descriptors found: 1
```

Flux HelmRelease manifest, which is created by `ocm-controller`:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  creationTimestamp: '2024-03-11T17:31:31Z'
  finalizers:
    - finalizers.fluxcd.io
  generation: 1
  name: ocm-hello-world-pod-info-file-system-tar
  namespace: ocm-system
  ownerReferences:
    - apiVersion: delivery.ocm.software/v1alpha1
      kind: FluxDeployer
      name: ocm-hello-world-pod-info-file-system-tar
      uid: 47e49bf2-4462-4b44-9750-e628376bef45
  resourceVersion: '345652'
  uid: 36e19345-c22b-4e32-853d-aaa0cd310d10
  selfLink: >-
    /apis/helm.toolkit.fluxcd.io/v2beta2/namespaces/ocm-system/helmreleases/ocm-hello-world-pod-info-file-system-tar
status:
  conditions:
    - lastTransitionTime: '2024-03-11T17:31:32Z'
      message: Fulfilling prerequisites
      observedGeneration: 1
      reason: Progressing
      status: 'True'
      type: Reconciling
    - lastTransitionTime: '2024-03-11T17:31:41Z'
      message: >-
        HelmChart
        'ocm-system/ocm-system-ocm-hello-world-pod-info-file-system-tar' is not
        ready: chart pull error: failed to download chart for remote reference:
        failed to get
        'oci://registry.ocm-system.svc.cluster.local:5000/sha-2684113188136592673/podinfo:6.6.2':
        manifest does not contain minimum number of descriptors (2), descriptors
        found: 1
      observedGeneration: 1
      reason: HelmChartNotReady
      status: 'False'
      type: Ready
  helmChart: ocm-system/ocm-system-ocm-hello-world-pod-info-file-system-tar
  observedGeneration: -1
spec:
  chart:
    spec:
      chart: podinfo
      interval: 10s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ocm-hello-world-pod-info-file-system-tar
        namespace: ocm-system
      version: '*'
  interval: 10s
  releaseName: pod-info-file-system-tar
  targetNamespace: default
```

Lookup of manifest within local cluster OCM registry:

```shell
crane catalog 127.0.0.1:5000 --insecure                                                 
sha-2684113188136592673/podinfo
sha-4656385248527026727/podinfo
crane manifest 127.0.0.1:5000/sha-2684113188136592673/podinfo:6.6.2 --insecure |jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 233,
    "digest": "sha256:c6306263840b5fcb21a076949f238c0a65e854758d4d531c6ea0174e8a74bf59"
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
      "size": 15451,
      "digest": "sha256:c02caf5b7c9c4a3a6f0bf3ba78d7f20307c968b4352a8fa334868d6c0acdad33"
    }
  ]
}
➜  ocm-controller git:(main) ✗ crane manifest 127.0.0.1:5000/sha-4656385248527026727/podinfo:6.6.2 --insecure |jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.cncf.helm.config.v1+json",
    "size": 233,
    "digest": "sha256:3c6315a9a1628305b60407757a499d24b4952b90091c65b95e0994304c2c0f49"
  },
  "layers": [
    {
      "mediaType": "application/vnd.cncf.helm.chart.content.v1.tar+gzip",
      "size": 16732,
      "digest": "sha256:9f0b717d25474c87de5dbd0a588829bdf4fa52c3f9bc9bb169e00b4935a87cc9"
    }
  ]
}
```

Environment:

```
ocm version
{"Major":"0", "Minor":"7", "Patch":"0", "PreRelease":"", "Meta":"", "GitVersion":"0.7.0", "GitCommit":"a2b9f7464074572632c40feb4db19c65b5cedd94", "GitTreeState":"", "BuildDate":"2024-02-23T17:20:54Z", "GoVersion":"go1.21.7", "Compiler":"gc", "Platform":"darwin/arm64"}

 sw_vers
ProductName:		macOS
ProductVersion:		14.3.1
BuildVersion:		23D60

system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.3.1 (23D60)
      Kernel Version: Darwin 23.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ....
      User Name: sb (I5....)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: X Tage, 1 Stunde und 28 Minuten
```

**Comment by stb1337** [comment]
I was able to solve this one by myself with this correction:

```yaml
- name: pod-info-file-system-tar
    #type: fileSystem
    type: helmChart
    version: *version
    input:      
      type: helm
      path: podinfo-6.6.0.tar
```

Why was I able to build&push `input.type: helm` when using `type:fileSystem`?
