### ISSUE TITLE
ocm-controller CrashLoopBackOff due to panic in reconciliation of the ComponentVersion when constructing the component descriptors for references

### ISSUE THREAD

**Issue by jonasbreuer** [open-component-model/ocm-controller#429]
Running into the following panic error resulting in a CrashLoopBackOff.
In my use-case I am having 1 component descriptor referring n component descriptors which also refers n component descriptors.
I have seen that the first component descriptor and it first reference of the main comp desc seems to be successful as the ComponentDescriptor CR's are created.

ocm-controller logs:
```
2024-05-26T16:19:43Z	INFO	Version check succeeded, found latest version: 1.0.10	{"name": "dwc.tools.sap.dwc-project.dwc-dev.landscape.dev-eu10-k8s-orbits", "namespace": "ocm-system", "reconciler kind": "ComponentVersion", "reason": "Progressing", "annotations": {}}
2024-05-26T16:19:43Z	DEBUG	events	Version check succeeded, found latest version: 1.0.10	{"type": "Normal", "object": {"kind":"ComponentVersion","namespace":"ocm-system","name":"dwc.tools.sap.dwc-project.dwc-dev.landscape.dev-eu10-k8s-orbits","uid":"3e39a7ac-f171-4e4f-ab25-31dc40ad5020","apiVersion":"delivery.ocm.software/v1alpha1","resourceVersion":"197219586"}, "reason": "Progressing"}
2024-05-26T16:19:46Z	ERROR	Reconciliation did not succeed, retrying in 10s	{"name": "dwc.tools.sap.dwc-project.dwc-dev.landscape.dev-eu10-k8s-orbits", "namespace": "ocm-system", "reconciler kind": "ComponentVersion", "annotations": {"delivery.ocm.software/component_version":":"}, "error": "Progressing"}
github.com/fluxcd/pkg/runtime/events.(*Recorder).AnnotatedEventf
	/home/runner/go/pkg/mod/github.com/fluxcd/pkg/runtime@v0.35.0/events/recorder.go:137
github.com/open-component-model/ocm-controller/pkg/event.New
	/home/runner/work/ocm-controller/ocm-controller/pkg/event/event.go:31
github.com/open-component-model/ocm-controller/pkg/status.UpdateStatus
	/home/runner/work/ocm-controller/ocm-controller/pkg/status/register_status_defer.go:31
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).Reconcile.func1
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:146
runtime.gopanic
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/panic.go:770
runtime.panicmem
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/panic.go:261
runtime.sigpanic
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/signal_unix.go:881
github.com/open-component-model/ocm-controller/pkg/ocm.(*Client).GetComponentVersion
	/home/runner/work/ocm-controller/ocm-controller/pkg/ocm/ocm.go:276
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).constructComponentDescriptorsForReference
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:411
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).parseReferences
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:394
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).constructComponentDescriptorsForReference
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:434
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).parseReferences
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:394
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).reconcile
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:315
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).Reconcile
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:230
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235
2024-05-26T16:19:46Z	DEBUG	events	Reconciliation did not succeed, retrying in 10s	{"type": "Warning", "object": {"kind":"ComponentVersion","namespace":"ocm-system","name":"dwc.tools.sap.dwc-project.dwc-dev.landscape.dev-eu10-k8s-orbits","uid":"3e39a7ac-f171-4e4f-ab25-31dc40ad5020","apiVersion":"delivery.ocm.software/v1alpha1","resourceVersion":"197219586"}, "reason": "Progressing"}
2024-05-26T16:19:46Z	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "componentversion", "controllerGroup": "delivery.ocm.software", "controllerKind": "ComponentVersion", "ComponentVersion": {"name":"dwc.tools.sap.dwc-project.dwc-dev.landscape.dev-eu10-k8s-orbits","namespace":"ocm-system"}, "namespace": "ocm-system", "name": "dwc.tools.sap.dwc-project.dwc-dev.landscape.dev-eu10-k8s-orbits", "reconcileID": "70509b16-9485-4d25-bbd1-85208d71abb9"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x2687198]

goroutine 381 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1e5
panic({0x2c87560?, 0x51c4910?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/panic.go:770 +0x132
github.com/open-component-model/ocm-controller/pkg/ocm.(*Client).GetComponentVersion(0x316c400?, {0x316c400?, 0xc000c30600?}, {0x0, 0x0}, 0xc000c30600?, {0xc00195ef50, 0x45}, {0xc001ef8f78, 0x14})
	/home/runner/work/ocm-controller/ocm-controller/pkg/ocm/ocm.go:276 +0x98
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).constructComponentDescriptorsForReference(0xc0005c0e00, {0x3701070, 0xc0005ffe00}, {0x0?, 0x0?}, 0xc00093e008, {{{0xc001ef8f60, 0x12}, {0xc001ef8f78, 0x14}, ...}, ...})
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:411 +0xae
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).parseReferences(0xc0005c0e00, {0x3701070, 0xc0005ffe00}, {0x0, 0x0}, 0xc00093e008, {0xc00097b4a0?, 0x2?, 0xc000dab260?})
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:394 +0x16a
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).constructComponentDescriptorsForReference(0xc0005c0e00, {0x3701070, 0xc0005ffe00}, {0x373c048?, 0xc000d5ab10?}, 0xc00093e008, {{{0xc000eeedb0, 0x10}, {0xc000eeed94, 0x5}, ...}, ...})
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:434 +0x419
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).parseReferences(0xc0005c0e00, {0x3701070, 0xc0005ffe00}, {0x373c048, 0xc000d5ab10}, 0xc00093e008, {0xc000a42660?, 0xb?, 0x325f66b?})
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:394 +0x16a
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).reconcile(0xc0005c0e00, {0x3701070, 0xc0005ffe00}, {0x373c048, 0xc000d5ab10}, 0xc00093e008, {0xc001b0054a, 0x6})
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:315 +0x6c5
github.com/open-component-model/ocm-controller/controllers.(*ComponentVersionReconciler).Reconcile(0xc0005c0e00, {0x3701070, 0xc0005ffe00}, {{{0xc000c14610?, 0x0?}, {0xc00026bfc0?, 0xc0005ffe00?}}})
	/home/runner/work/ocm-controller/ocm-controller/controllers/componentversion_controller.go:230 +0x896
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x3701070?, {0x3701070?, 0xc0005ffe00?}, {{{0xc000c14610?, 0x2b18040?}, {0xc00026bfc0?, 0xc000985ac0?}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000644a00, {0x37010a8, 0xc0007031d0}, {0x2dc9880, 0xc0008891c0})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x345
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000644a00, {0x37010a8, 0xc0007031d0})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1be
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 143
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x50c
```

Component Descriptor no.1:
```yaml
component:
  componentReferences:
  - componentName: dwc.tools.sap/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits/lpi-opb2mres765vvpr4
    labels:
    - name: dwc.tools.sap/dwc-vector-id
      value: 0182f823-0c5d-d606-2985-c187971ad569
      version: v1
    - name: dwc.tools.sap/dwc-landscape-partition-instance-state
      value: SUCCESS
      version: v1
    name: opb2mres765vvpr4
    version: 1.0.0
  - componentName: dwc.tools.sap/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits/lpi-ccyofiqmiirtmv43
    labels:
    - name: dwc.tools.sap/dwc-vector-id
      value: 018fb041-abf7-12f4-d347-c139ddff688a
      version: v1
    - name: dwc.tools.sap/dwc-landscape-partition-instance-state
      value: SUCCESS
      version: v1
    name: ccyofiqmiirtmv43
    version: 1.0.0
  - componentName: dwc.tools.sap/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits/lpi-xvgmwhpoueohwgv6
    labels:
    - name: dwc.tools.sap/dwc-vector-id
      value: 018fb577-cfba-6e3a-52e9-65052a67b0ba
      version: v1
    - name: dwc.tools.sap/dwc-landscape-partition-instance-state
      value: SUCCESS
      version: v1
    name: xvgmwhpoueohwgv6
    version: 1.0.0
  - componentName: dwc.tools.sap/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits/lpi-w4ilhzjyueelp54y
    labels:
    - name: dwc.tools.sap/dwc-vector-id
      value: 018fb582-6fe8-6422-de3d-d06e8793691c
      version: v1
    - name: dwc.tools.sap/dwc-landscape-partition-instance-state
      value: CREATING
      version: v1
    name: w4ilhzjyueelp54y
    version: 1.0.0
  labels:
  - name: dwc.tools.sap/dwc-project
    value: dwc-dev
    version: v1
  - name: dwc.tools.sap/dwc-landscape
    value: dev-eu10-k8s-orbits
    version: v1
  name: dwc.tools.sap/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits
  provider: dwc.tools.sap
  repositoryContexts: []
  resources:
  - access:
      imageReference: eu.gcr.io/sap-dwc/ocm-deployment/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits/component-descriptors/dwc.tools.sap/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits@sha256:614e079efb39260fada4608139f3b294c698c653bfd4ef2f45ebe50ac20d6b09
      type: ociArtifact
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: ociArtifactDigest/v1
      value: 614e079efb39260fada4608139f3b294c698c653bfd4ef2f45ebe50ac20d6b09
    name: dwc-landscape-vector-deployments
    relation: local
    type: helmChart
    version: 1.0.0
  sources: []
  version: 1.0.6
meta:
  schemaVersion: v2
```

Component Descriptor no.2 (reference of no.1):
```yaml
component:
  componentReferences:
  - componentName: github.tools.sap/deploy-with-confidence-trial/picture-storage-service
    name: appname-todo-ruxau
    version: 1.0.5-20240410082017
  - componentName: github.tools.sap/undefined.lhpxbjpsoshohjpk
    name: appname-todo-quqhl
    version: 1.0.5-20240410082017
  labels:
  - name: dwc.tools.sap/dwc-project
    value: dwc-dev
    version: v1
  - name: dwc.tools.sap/dwc-landscape
    value: dev-eu10-k8s-orbits
    version: v1
  - name: dwc.tools.sap/dwc-landscape-partition-instance-id
    value: W4ILHZJYUEELP54Y
    version: v1
  name: dwc.tools.sap/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits/lpi-w4ilhzjyueelp54y
  provider: dwc.tools.sap
  repositoryContexts: []
  resources:
  - access:
      imageReference: eu.gcr.io/sap-dwc/ocm-deployment/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits/component-descriptors/dwc.tools.sap/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits/lpi-w4ilhzjyueelp54y@sha256:25540e190e2cc44fa9bbd8ecda7dab3752778860be1de542bd7c413f31d897b9
      type: ociArtifact
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: ociArtifactDigest/v1
      value: 25540e190e2cc44fa9bbd8ecda7dab3752778860be1de542bd7c413f31d897b9
    name: dwc-landscape-partition-instance-helm-chart
    relation: local
    type: helmChart
    version: 1.0.0
  sources: []
  version: 1.0.0
meta:
  schemaVersion: v2
```

Component Descriptor no.3 (reference of no.2):
```yaml
component:
  componentReferences: []
  labels:
  - name: dwc.tools.sap/dwc-project
    value: dwc-dev
    version: v1
  - name: dwc.tools.sap/dwc-landscape
    value: dev-eu10-k8s-orbits
    version: v1
  - name: dwc.tools.sap/dwc-landscape-partition-instance-id
    value: W4ILHZJYUEELP54Y
    version: v1
  - name: dwc.tools.sap/dwc-artifact-id
    value: 018e2d34-7282-a9c0-3ea3-1406933f1c22
    version: v1
  - name: dwc.tools.sap/dwc-appname
    value: appname-todo-ruxau
    version: v1
  name: github.tools.sap/deploy-with-confidence-trial/picture-storage-service
  provider: github.tools.sap/deploy-with-confidence-trial
  repositoryContexts: []
  resources:
  - access:
      imageReference: eu.gcr.io/sap-dwc/ocm-deployment/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits/component-descriptors/github.tools.sap/deploy-with-confidence-trial/picture-storage-service@sha256:488c33687d08f5b410888fd44f6ae4eb5015fecfb79e9f0d65bd35e6b6019c13
      type: ociArtifact
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: ociArtifactDigest/v1
      value: 488c33687d08f5b410888fd44f6ae4eb5015fecfb79e9f0d65bd35e6b6019c13
    name: dwc-artifact-deployment-helm-chart
    relation: local
    type: helmChart
    version: 0.0.1
  - access:
      imageReference: eu.gcr.io/sap-dwc/ocm-deployment/dwc-project/dwc-dev/landscape/dev-eu10-k8s-orbits/component-descriptors/github.tools.sap/deploy-with-confidence-trial/picture-storage-service@sha256:617d2f49df1fd7956168757e7af0e8e69e4fe70e5e712f0e7a4695c2d167fd0a
      type: ociArtifact
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: ociArtifactDigest/v1
      value: 617d2f49df1fd7956168757e7af0e8e69e4fe70e5e712f0e7a4695c2d167fd0a
    name: dwc-artifact-assignment-helm-chart
    relation: local
    type: helmChart
    version: 1.0.0
  - access:
      localReference: sha256:603bbba677daadf98471397efc0da4f884a85c817662f8e961ed8a9267b1d95a
      mediaType: application/x-yaml
      referenceName: appname-todo-kirdo-config
      type: localBlob
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: genericBlobDigest/v1
      value: 603bbba677daadf98471397efc0da4f884a85c817662f8e961ed8a9267b1d95a
    name: appname-todo-kirdo-config
    relation: local
    type: configdata.ocm.software
    version: 1.0.5-20240410082017
  - access:
      imageReference: eu.gcr.io/sap-dwc/picture-storage-service:1.0.0-20240311110312
      type: ociArtifact
    name: appname-todo-kirdo-image
    relation: external
    type: ociImage
    version: 1.0.0-20240311110312
  - access:
      localReference: sha256:603bbba677daadf98471397efc0da4f884a85c817662f8e961ed8a9267b1d95a
      mediaType: application/x-yaml
      referenceName: appname-todo-gepyt-config
      type: localBlob
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: genericBlobDigest/v1
      value: 603bbba677daadf98471397efc0da4f884a85c817662f8e961ed8a9267b1d95a
    name: appname-todo-gepyt-config
    relation: local
    type: configdata.ocm.software
    version: 1.0.5-20240410082017
  - access:
      localReference: sha256:603bbba677daadf98471397efc0da4f884a85c817662f8e961ed8a9267b1d95a
      mediaType: application/x-yaml
      referenceName: appname-todo-gabew-config
      type: localBlob
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: genericBlobDigest/v1
      value: 603bbba677daadf98471397efc0da4f884a85c817662f8e961ed8a9267b1d95a
    name: appname-todo-gabew-config
    relation: local
    type: configdata.ocm.software
    version: 1.0.5-20240410082017
  - access:
      localReference: sha256:603bbba677daadf98471397efc0da4f884a85c817662f8e961ed8a9267b1d95a
      mediaType: application/x-yaml
      referenceName: appname-todo-oxwya-config
      type: localBlob
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: genericBlobDigest/v1
      value: 603bbba677daadf98471397efc0da4f884a85c817662f8e961ed8a9267b1d95a
    name: appname-todo-oxwya-config
    relation: local
    type: configdata.ocm.software
    version: 1.0.5-20240410082017
  - access:
      localReference: sha256:603bbba677daadf98471397efc0da4f884a85c817662f8e961ed8a9267b1d95a
      mediaType: application/x-yaml
      referenceName: appname-todo-ruxau-config
      type: localBlob
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: genericBlobDigest/v1
      value: 603bbba677daadf98471397efc0da4f884a85c817662f8e961ed8a9267b1d95a
    name: appname-todo-ruxau-config
    relation: local
    type: configdata.ocm.software
    version: 1.0.5-20240410082017
  sources:
  - access:
      apiHostname: github.tools.sap
      commit: 15c11b957b0eb9d397c16683346cfdf51c1ed82a
      repoUrl: https://github.tools.sap/deploy-with-confidence-trial/picture-storage-service
      type: gitHub
    name: github-repository
    type: gitHub/v1
    version: 1.0.5-20240410082017
  version: 1.0.5-20240410082017
meta:
  schemaVersion: v2
```
