### ISSUE TITLE
Failed to deploy the ocm-controller via flux

### ISSUE THREAD

**Issue by nexus49** [open-component-model/ocm-controller#510]
I am seeing issues to deploy the ocm-controller with flux.

Resulting in the ocm pods in a state `ContainerCreating`:
```
NAME                              READY   STATUS              RESTARTS   AGE
ocm-controller-7c9bcc8654-lhlbg   0/1     ContainerCreating   0          30m
registry-67cf9d786d-d6w9s         0/1     ContainerCreating   0          30m
```

Error in the pod is: 
```
MountVolume.SetUp failed for volume "certificates" : secret "ocm-registry-tls-certs" not found
```

Please see this minimal script to reproduce the issue:
```
kind create cluster -n ocm
flux install --components source-controller,helm-controller
kubectl apply -f - <<EOF
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ocm-controller
  namespace: default
spec:
  interval: 5m
  url: oci://ghcr.io/open-component-model/helm/ocm-controller
  ref:
    semver: "v0.24.0"

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocm
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: ocm-controller
  releaseName: ocm-controller
  values:
    cert-manager:
      enabled: "true"
EOF
```
