### ISSUE TITLE
Refactor Localizer to Localization

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-controller#6]
## Description

As part of efforts to consolidate the `ocm-controller` we will refactor the `Localizer` controller so that it becomes a sub-controller managed by the `ocm-controller`. As part of the refactoring, the `Localizer` controller will be renamed `Localization`.

The major functional change required is to add support for `Snapshot`s. The `Localization` controller should be able to consume resources from a Snapshot and should produce a Snapshot as it's output.

## CRD

```yaml
apiVersion: toolkit.ocm.software/v1alpha1
kind: Localization
metadata:
  name: test
spec:
  sourceRef: # provides information about accessing the resource to be transformed
    kind: Snapshot | ComponentVersion
    name: my-snapshot
  configRef: # provides information about accessing the resource which contains the localization parameters
    kind: Snapshot | ComponentVersion
    name: podinfo-component
    resource: ocm-config
  snapshotTemplate: # provides
    name: localized-snapshot
    labels:
      owner: piaras.hoban

```

## Sequence

```mermaid
sequenceDiagram
User ->> Kubernetes API: submit Localization CR

Kubernetes API ->> Localization Controller: new Localization event

Localization Controller ->> OCM Controller: request Component Descriptor

OCM Controller ->> Localization Controller: return Component Descriptor

Localization Controller ->> Localization Controller: get access location of target resource from Component Descriptor

Localization Controller ->> OCM Controller: request target resource

OCM Controller ->> OCM Registry: request target resource on behalf of Localization

OCM Registry ->> OCM Controller: return target resource

OCM Controller ->> Local Registry: store target resource

OCM Controller ->> Localization Controller: return target resource

Localization Controller ->> Localization Controller: get access location of config resource from Component Descriptor

Localization Controller ->> OCM Controller: request config resource

OCM Controller ->> OCM Registry: request config resource on behalf of Localizer

OCM Registry ->> OCM Controller: return config resource

OCM Controller ->> Local Registry: store config resource

OCM Controller ->> Localization Controller: return config resource

Localization Controller -->> Localization Controller: execute localization on target resource using data from config resource

Localization Controller ->> Local Registry: push output as OCI artifact

Localization Controller ->> Kubernetes API: create/update Snapshot CR with location of OCI artifact

Localization Controller -->> Localization Controller: wait reconcile interval
```

## Tasks:

- [ ] Add Localization CRD
- [ ] Implement Localization Controller as part of ocm-controller
