### ISSUE TITLE
Version of the Resource should default to the Version specified in the ComponentVersion's Resource.

### ISSUE THREAD

**Issue by nexus49** [open-component-model/ocm-controller#629]
**Context**  
As a user, when deploying with the OCM Controller, it should be possible to only specify the version of the `ComponentVersion` CR without the need to specify any other version in any of the other CR's like `Resource`.

Example for clarification:

> [!NOTE]  
> The following example was constructed manually and shortened for clarify.

`component-a (0.0.5)` -- references --> `component-b (0.5.19)` -- has resource --> `chart (0.3.19)`

ComponentVersion `component-a`
```
component:
  componentReferences:
  - componentName: github.com/mycorp/component-b
    name: component-b
    version: 0.3.19
  name: github.com/mycorp/component-a
  resources: []
  sources: []
  version: 0.0.5
meta:
  schemaVersion: v2
```

ComponentVersion  `component-b`
```
component:
  componentReferences: []
  name: github.com/mycorp/component-b
  version: 0.5.19
  resources:
  - access:
      imageReference: ghcr.io/mycorp/charts/component-b:0.3.19
      type: ociArtifact
    name: chart
    relation: external
    type: helmChart
    version: 0.3.19
  - name: image
    relation: external
    type: ociImage
    version: v0.90.12
meta:
  schemaVersion: v2
```

In Order to Deploy the chart of component-b the following CRs are created:

ComponentVersion for `component-a`
```
apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: component-a
spec:
  component: github.com/mycorp/component-a
  repository:
    url: mycorp.com/repo/ocm
  version:
    semver: 0.0.5
```

Resource for the chart in `component-b`
```
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: component-b-chart
spec:
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: ComponentVersion
    name: component-a
    resourceRef:
      name: chart
      referencePath:
      - name: component-b
```

FluxDeployer
```
apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: component-b
spec:
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: component-b-chart
```

**Version**  
v0.24.13

**Actual behavior**  
As the `Resource` `component-b-chart` does not specify any version currently the ocm-controller will assume the version to be `latest`. In flux the deployment will then fail with the error: `failed parsing artifact revision latest`

**Expected behavior**  
The ocm-controller should make use of the available componentVersion and componentDescriptors to follow a similar path:
- get to the applied ComponentVersion (0.0.5)
- use the `resource.sourceRef.referencePath` to determine the correct referenced componentVersion (0.5.19)
- get the `ComponentDescriptor` of given referenced componentVersion
- in the `ComponentDescriptor` of component-b identify the resource with the name as specified in `resource.sourceRef.name` and determine the correct version (0.3.19)

**Environment**  
- [ ] windows
- [x] linux
- [x] mac
