### ISSUE TITLE
Refactor Configurator to Configuration

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-controller#7]
## Description

As part of efforts to consolidate the ocm-controller we will refactor the Configurator controller so that it becomes a sub-controller managed by the ocm-controller. As part of the refactoring, the Configurator controller will be renamed Configuration.

The major functional change required is to add support for Snapshots. The Configuration controller should be able to consume resources from a Snapshot and should produce a Snapshot as it's output.

`Configuration` requires two inputs, one for the resource to process (`spec.sourceRef`) and another which contains the configuration values and substitution rules (`configRef`). These input fields may reference either `Snapshot` or `ComponentVersion` kinds.

## CRD

```yaml
apiVersion: ocm.software/v1alpha1
kind: Configuration
metadata:
  name: component-config
spec:
  sourceRef:
    kind: Snapshot
    name: my-snapshot
    resource: manifests-localized
  configRef:
    kind: ComponentVersion
    name: my-component
    resource: ocm-config
    path: configuration # default
  values: 
     color: red
     debug: 1
  snapshotTemplate:
      name: manifests-configured
```

## Sequence

```mermaid
sequenceDiagram
User ->> Kubernetes API: submit Configuration CR

Kubernetes API ->> Configuration Controller: new Configuration event

Configuration Controller ->> OCM Controller: request Component Descriptor

OCM Controller ->> Configuration Controller: return Component Descriptor

Configuration Controller ->> Configuration Controller: get access location of target resource from Component Descriptor

Configuration Controller ->> OCM Controller: request target resource

OCM Controller ->> OCM Registry: request target resource on behalf of Localization

OCM Registry ->> OCM Controller: return target resource

OCM Controller ->> Local Registry: store target resource

OCM Controller ->> Configuration Controller: return target resource

Configuration Controller ->> Configuration Controller: get access location of config resource from Component Descriptor

Configuration Controller ->> OCM Controller: request config resource

OCM Controller ->> OCM Registry: request config resource on behalf of Localizer

OCM Registry ->> OCM Controller: return config resource

OCM Controller ->> Local Registry: store config resource

OCM Controller ->> Configuration Controller: return config resource

Configuration Controller -->> Configuration Controller: execute configuration on target resource using data from config resource

Configuration Controller ->> Local Registry: push output as OCI artifact

Configuration Controller ->> Kubernetes API: create/update Snapshot CR with location of OCI artifact

Configuration Controller -->> Configuration Controller: wait reconcile interval
```

## Tasks:

- [ ] Add Configuration CRD
- [ ] Implement Configuration Controller as part of ocm-controller
