### ISSUE TITLE
Create Snapshot controller

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-controller#8]
## Description

Snapshot's make it possible for us to perform sequences of actions without requiring any strong coupling between controllers. An `Snapshot` is a namespaced Kubernetes resource which contains metadata about a Flux compatible OCI artifact which is stored in an OCI registry managed by the ocm-controller.

The snapshot controller is responsible for cleaning up snapshots when the parent resource is deleted.

The snapshot controller may also handle verification of snapshots at some future point.

## CRD
```yaml
apiVersion: delivery.com.software/v1alpha1
kind: Snapshot
metadata:
   name: test
   namespace: default
spec:
  ref: resource-name
status:
 url: compoonent-name/resource-name:latest
```
