### ISSUE TITLE
Support CUE for complex mappings in Localization

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-controller#85]
## Description 

Currently the mappings provided by localization are limited to the elements of a docker image reference.

In order to allow for arbitrary mapping strategies we should explore the use of CUE as a means by which to express the mapping.  

## Possible Approach

The below outlines one way in which the api for this might look. We provide the mapping details using a ConfigData file as usual but instead of specifying a particular resource to use for the localization, we pass the entire component-descriptor into the CUE script as a data variable. This can then be used within the `mapping` script to generate appropriate output. The output is returned to the controller and patched into the specified file as the given path.

```yaml
apiVersion: config.ocm.software/v1alpha1
kind: ConfigData
metadata:
  name: ocm-config
  labels:
    env: test
localization:
# the component descriptor is passed to the cue mapping expression
# the mapping expression generates some data which is returned to the localization controller via the "out" variable.
# the contents of out are inserted into the file "deploy.yaml" at the path "spec.servicePresets.images"
- file: bizx_environment.yaml
  path: spec.servicePresets.images
  mapping: |
    package main

    import (
      "encoding/yaml"
      "strings"
    )

    # the variable "component" is populated
    # with the component descriptor data
    images: {
      for r in component.resources {
        let name = strings.Replace(r.name, "bizx-", "", -1)
        "\(name)": r.access.imageReference
      }
    }

    out: yaml.Marshal(images)
```

For a component descriptor containing the following resources:

```yaml
resources:
  - name: bizx-logstash
    version: "0.1.5-7.17.6"
    type: ociImage
    access:
      type: ociRegistry
      imageReference: sf-docker-golden.common.cdn.repositories.cloud.sap/bizx-sidecars/logstash:0.1.5-7.17.6
  - name: bizx-grafana
    version: "0.1.5-7.17.6"
    type: ociImage
    access:
      type: ociRegistry
      imageReference: sf-docker-golden.common.cdn.repositories.cloud.sap/bizx-sidecars/grafana:0.1.5-7.17.6
```
The above cue mapping would generate the following output:

```yaml
logstash: sf-docker-golden.common.cdn.repositories.cloud.sap/bizx-sidecars/logstash:0.1.5-7.17.6
grafana: sf-docker-golden.common.cdn.repositories.cloud.sap/bizx-sidecars/grafana:0.1.5-7.17.6
```

Which would be patched into the file `bizx_environment.yaml`  at the path `spec.servicePresets.images`  resulting in the following localized resource:

```yaml
apiVersion: sapsf.com/v1alpha1
kind: BizxEnvironment
spec:
  servicePresets:
    images:
      logstash: sf-docker-golden.common.cdn.repositories.cloud.sap/bizx-sidecars/logstash:0.1.5-7.17.6
      grafana: sf-docker-golden.common.cdn.repositories.cloud.sap/bizx-sidecars/grafana:0.1.5-7.17.6
```
