### ISSUE TITLE
Use `Resource` to facilitate requesting resources in Localization & Configuration controllers

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-controller#9]
## Description

Controllers such as `Localization` and `Configuration` should be able to consume resources from an existing snapshot or from a `ComponentVersion`. `spec.sourceRef.kind` for instance should accept either a `Snapshot` or `ComponentVersion`. When `ComponentVersion` is specified the controller should create an `Resource` object using the given parameters. The controller should then process the snapshot created by this `Resource` as normal.

```yaml
apiVersion: ocm.software/v1alpha1
kind: Configuration
metadata:
  name: string
spec:
  sourceRef:
    kind: Snapshot | ComponentVersion
    name: string
  configRef:
    kind: Snapshot | ComponentVersion
    name: string # component name
    resource:  string # config resource name
```
